baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Iris Design Thoughts'
theme = "hugo-bearcub"
copyright = "IrisLikeThePlant (CC BY 4.0)"
defaultContentLanguage = "en"

enableRobotsTXT = true

[params]
madeWith = "Made with [Bear Cub](https://github.com/clente/hugo-bearcub)"
description = "Random thoughts by a game designer on game design"
title = "Iris' Design Thoughts"

[params.social]
bluesky = "@kyliedev"